using System;
using System.Collections.Generic;
using System.Text;

namespace krugerEvaluacion.Core.DTOs
{
    public class PropietarioDto
    {
        // <summary>
        /// Autogenerated id for post entity
        /// </summary>
        public int Id { get; set; }
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Mail { get; set; }
        public int UserId { get; set; }
    }
}
